/**
 * PORTFOLIO MAIN JS
 * Reads everything from js/config.js and builds the page.
 * Do NOT edit this file for content — edit js/config.js instead.
 */

/* ══ Wait for DOM ══ */
document.addEventListener('DOMContentLoaded', () => {
  // Try window.PORTFOLIO_CONFIG (set by config.js)
  const C = window.PORTFOLIO_CONFIG || (typeof PORTFOLIO_CONFIG !== 'undefined' ? PORTFOLIO_CONFIG : null);
  if (!C) {
    document.body.innerHTML = '<div style="color:#f87171;font-family:monospace;padding:40px;font-size:1rem;">⚠️ config.js not loaded. Please make sure js/config.js exists.</div>';
    return;
  }

  buildPage(C);
  initNavbar();
  initToggle();
  initTyping(C.settings.typingTexts || [C.personal.tagline]);
  initSkillBars();
  initActiveNav();
  initBackToTop();
  initContactForm();
  initScrollReveal();
});

/* ══════════════════════════════════════════════
   BUILD PAGE FROM CONFIG
══════════════════════════════════════════════ */
function buildPage(C) {
  const p = C.personal;
  const s = C.settings;

  /* ── <title> & meta ── */
  document.getElementById('pageTitle').textContent = `${p.name} — ${p.tagline}`;
  document.getElementById('metaDesc').setAttribute('content', p.summary);

  /* ── Navbar ── */
  document.getElementById('navInitials').textContent = p.initials || p.name.slice(0,2).toUpperCase();
  document.getElementById('navName').textContent     = p.name;

  /* ── Hero ── */
  document.getElementById('heroName').textContent    = p.name;
  document.getElementById('heroSummary').textContent = p.summary;

  // Photo (hero)
  if (s.showPhoto && p.photo) {
    const wrap = document.getElementById('heroPhotoWrap');
    const av   = document.getElementById('heroAvatar');
    av.innerHTML = `<img src="${p.photo}" alt="${p.name}" />`;
    wrap.style.display = 'block';
  }

  // Stats
  const statsRow = document.getElementById('statsRow');
  if (C.stats && C.stats.length) {
    statsRow.innerHTML = C.stats.map(st => `
      <div class="stat-item">
        <span class="stat-n">${st.number}</span>
        <span class="stat-l">${st.label}</span>
      </div>`).join('');
  }

  /* ── About ── */
  document.getElementById('aboutRole').textContent    = p.tagline;
  document.getElementById('aboutSummary').textContent = p.summary;

  // Photo (about col)
  const aboutLayout = document.querySelector('.about-layout');
  if (s.showPhoto && p.photo) {
    const col   = document.getElementById('aboutPhotoCol');
    const frame = document.getElementById('aboutPhotoFrame');
    frame.innerHTML = `<img src="${p.photo}" alt="${p.name}" />`;
    col.style.display = 'block';
    aboutLayout.classList.add('has-photo');
  }

  // Info grid
  const addr = C.address;
  const addrStr = [addr.village, addr.city, addr.district, addr.state, addr.country]
                    .filter(Boolean).join(', ');

  const infoItems = [
    { icon: 'fas fa-user',           label: 'Full Name',  val: p.name,     link: '' },
    { icon: 'fas fa-briefcase',      label: 'Role',       val: p.tagline,  link: '' },
    { icon: 'fas fa-phone',          label: 'Phone',      val: p.phone ? '+91 ' + p.phone : '',  link: p.phone ? `tel:+91${p.phone}` : '' },
    { icon: 'fas fa-envelope',       label: 'Email',      val: p.email,    link: p.email ? `mailto:${p.email}` : '' },
    { icon: 'fas fa-map-marker-alt', label: 'Location',   val: addrStr,    link: '' },
    { icon: 'fas fa-graduation-cap', label: 'Qualification', val: (C.education[0] || {}).short || '', link: '' },
    ...(p.linkedin ? [{ icon: 'fab fa-linkedin', label: 'LinkedIn', val: 'View Profile', link: p.linkedin }] : []),
    ...(p.website  ? [{ icon: 'fas fa-globe',    label: 'Website',  val: p.website,     link: p.website  }] : []),
  ].filter(i => i.val);

  document.getElementById('infoGrid').innerHTML = infoItems.map(i => `
    <div class="info-item">
      <span class="info-lbl"><i class="${i.icon}"></i> ${i.label}</span>
      <span class="info-val">${i.link
        ? `<a href="${i.link}" ${i.link.startsWith('http') ? 'target="_blank"' : ''}>${i.val}</a>`
        : i.val}</span>
    </div>`).join('');

  // Languages
  const langMap = { native:'native', advanced:'advanced' };
  document.getElementById('langBlock').innerHTML = `
    <h4>Languages</h4>
    <div class="lang-tags">
      ${(C.languages || []).map(l => {
        const cls = langMap[(l.level || '').toLowerCase()] || 'other';
        return `<span class="lang-tag ${cls}">${l.name} — ${l.level}</span>`;
      }).join('')}
    </div>`;

  /* ── Skills ── */
  document.getElementById('skillsGrid').innerHTML = (C.skills || []).map(cat => `
    <div class="skill-cat">
      <div class="skill-cat-hd">
        <div class="skill-cat-icon"><i class="${cat.icon}"></i></div>
        <h3>${cat.category}</h3>
      </div>
      <div class="skill-rows">
        ${(cat.items || []).map(sk => `
          <div class="skill-row">
            <div class="skill-meta">
              <span>${sk.name}</span>
              <span>${sk.percent}%</span>
            </div>
            <div class="skill-bar">
              <div class="skill-fill" data-w="${sk.percent}"></div>
            </div>
          </div>`).join('')}
      </div>
    </div>`).join('');

  /* ── Experience ── */
  document.getElementById('experienceTimeline').innerHTML = (C.experience || []).map(ex => `
    <div class="tl-item">
      <div class="tl-dot"><i class="fas fa-hospital"></i></div>
      <div class="tl-card">
        <div class="tl-header">
          <div>
            <div class="tl-title">${ex.title}</div>
            <div class="tl-company">${ex.company}</div>
          </div>
          <div class="tl-meta">
            <span class="tl-period"><i class="fas fa-calendar-alt"></i> ${ex.period}</span>
            <span class="tl-type">${ex.type || 'Experience'}</span>
          </div>
        </div>
        <p class="tl-desc">${ex.description}</p>
        <ul class="tl-duties">
          ${(ex.duties || []).map(d => `<li><i class="fas fa-chevron-right"></i>${d}</li>`).join('')}
        </ul>
        <div class="tl-tags">
          ${(ex.tags || []).map(t => `<span>${t}</span>`).join('')}
        </div>
      </div>
    </div>`).join('');

  /* ── Education ── */
  document.getElementById('eduList').innerHTML = (C.education || []).map(ed => `
    <div class="edu-card">
      <div class="edu-period">${ed.period}</div>
      <div class="edu-degree">${ed.degree}</div>
      <span class="edu-short">${ed.short}</span>
      <div class="edu-institute"><i class="fas fa-building"></i>${ed.institute}</div>
      <p class="edu-desc">${ed.description}</p>
      <div class="edu-hi">
        ${(ed.highlights || []).map(h => `<span><i class="fas fa-star"></i>${h}</span>`).join('')}
      </div>
    </div>`).join('');

  /* ── Achievements ── */
  document.getElementById('achGrid').innerHTML = (C.achievements || []).map(a => `
    <div class="ach-card${a.featured ? ' featured' : ''}">
      <div class="ach-icon"><i class="${a.icon}"></i></div>
      <div class="ach-num">${a.number}</div>
      <div class="ach-title">${a.title}</div>
      <p class="ach-desc">${a.desc}</p>
      <span class="ach-badge">${a.badge}</span>
    </div>`).join('');

  // Strengths
  if (s.showStrengths && C.strengths && C.strengths.length) {
    document.getElementById('strengthsBlock').innerHTML = `
      <div class="strengths-block">
        <div class="strengths-title">Personal Strengths</div>
        <div class="strengths-grid">
          ${C.strengths.map(st => `
            <div class="str-item">
              <div class="str-icon"><i class="${st.icon}"></i></div>
              <div>
                <h4>${st.title}</h4>
                <p>${st.desc}</p>
              </div>
            </div>`).join('')}
        </div>
      </div>`;
  }

  /* ── Contact ── */
  const contactCards = [];
  if (p.phone)  contactCards.push({ icon:'fas fa-phone',          cls:'ph',  label:'Phone',    val:'+91 '+p.phone, link:'tel:+91'+p.phone });
  if (p.email)  contactCards.push({ icon:'fas fa-envelope',       cls:'em',  label:'Email',    val:p.email, link:'mailto:'+p.email });
  if (addrStr)  contactCards.push({ icon:'fas fa-map-marker-alt', cls:'loc', label:'Location', val:addrStr, link:'' });
  if (p.linkedin) contactCards.push({ icon:'fab fa-linkedin',     cls:'em',  label:'LinkedIn', val:'View Profile', link:p.linkedin });

  document.getElementById('contactCards').innerHTML = contactCards.map(cc => `
    <div class="contact-card">
      <div class="cc-icon ${cc.cls}"><i class="${cc.icon}"></i></div>
      <div>
        <div class="cc-label">${cc.label}</div>
        <div class="cc-val">${cc.link
          ? `<a href="${cc.link}" ${cc.link.startsWith('http')?'target="_blank"':''}>${cc.val}</a>`
          : cc.val}</div>
      </div>
    </div>`).join('');

  // Hide form if disabled
  if (!s.showContactForm) {
    const fw = document.getElementById('contactFormWrap');
    if (fw) fw.style.display = 'none';
  }

  /* ── Footer ── */
  document.getElementById('footerLeft').textContent  = `© ${new Date().getFullYear()} ${p.name}. All Rights Reserved.`;
  document.getElementById('footerRight').textContent = p.tagline;
}

/* ══════════════════════════════════════════════
   NAVBAR SCROLL
══════════════════════════════════════════════ */
function initNavbar() {
  const nav = document.getElementById('navbar');
  const onScroll = () => nav.classList.toggle('scrolled', window.scrollY > 40);
  window.addEventListener('scroll', onScroll, { passive: true });
  onScroll();
}

/* ══════════════════════════════════════════════
   MOBILE TOGGLE
══════════════════════════════════════════════ */
function initToggle() {
  const btn   = document.getElementById('navToggle');
  const links = document.getElementById('navLinks');
  if (!btn || !links) return;

  btn.addEventListener('click', () => links.classList.toggle('open'));

  links.querySelectorAll('.nl').forEach(a =>
    a.addEventListener('click', () => links.classList.remove('open'))
  );

  document.addEventListener('click', e => {
    if (!btn.contains(e.target) && !links.contains(e.target))
      links.classList.remove('open');
  });

  document.addEventListener('keydown', e => {
    if (e.key === 'Escape') links.classList.remove('open');
  });
}

/* ══════════════════════════════════════════════
   TYPING EFFECT
══════════════════════════════════════════════ */
function initTyping(strings) {
  const el = document.getElementById('typingText');
  if (!el || !strings.length) return;

  let si = 0, ci = 0, deleting = false;

  function tick() {
    const str = strings[si];
    if (!deleting) {
      el.textContent = str.slice(0, ++ci);
      if (ci === str.length) {
        deleting = true;
        setTimeout(tick, 2400);
        return;
      }
    } else {
      el.textContent = str.slice(0, --ci);
      if (ci === 0) {
        deleting = false;
        si = (si + 1) % strings.length;
      }
    }
    setTimeout(tick, deleting ? 45 : 80);
  }
  setTimeout(tick, 600);
}

/* ══════════════════════════════════════════════
   SKILL BAR ANIMATION
══════════════════════════════════════════════ */
function initSkillBars() {
  const fills = document.querySelectorAll('.skill-fill');
  if (!fills.length) return;

  const io = new IntersectionObserver(entries => {
    entries.forEach(e => {
      if (e.isIntersecting) {
        e.target.style.width = (e.target.dataset.w || 0) + '%';
        io.unobserve(e.target);
      }
    });
  }, { threshold: 0.3 });

  fills.forEach(f => io.observe(f));
}

/* ══════════════════════════════════════════════
   ACTIVE NAV LINK
══════════════════════════════════════════════ */
function initActiveNav() {
  const sections = document.querySelectorAll('section[id]');
  const links    = document.querySelectorAll('.nav-links .nl');

  const io = new IntersectionObserver(entries => {
    entries.forEach(e => {
      if (e.isIntersecting) {
        links.forEach(l => l.classList.remove('active'));
        const a = document.querySelector(`.nl[href="#${e.target.id}"]`);
        if (a) a.classList.add('active');
      }
    });
  }, { rootMargin: '-40% 0px -55% 0px' });

  sections.forEach(s => io.observe(s));
}

/* ══════════════════════════════════════════════
   BACK TO TOP
══════════════════════════════════════════════ */
function initBackToTop() {
  const btn = document.getElementById('btt');
  if (!btn) return;
  window.addEventListener('scroll', () => btn.classList.toggle('show', window.scrollY > 400), { passive: true });
  btn.addEventListener('click', () => window.scrollTo({ top: 0, behavior: 'smooth' }));
}

/* ══════════════════════════════════════════════
   CONTACT FORM
══════════════════════════════════════════════ */
function initContactForm() {
  const form = document.getElementById('contactForm');
  if (!form) return;

  form.addEventListener('submit', async e => {
    e.preventDefault();
    const btn  = document.getElementById('cfSubmit');
    const orig = btn.innerHTML;

    btn.innerHTML = '<i class="fas fa-spinner fa-spin"></i> Sending…';
    btn.disabled  = true;

    await new Promise(r => setTimeout(r, 1400));

    btn.innerHTML = '<i class="fas fa-check"></i> Sent!';
    btn.style.background = '#10b981';
    showToast();
    form.reset();

    setTimeout(() => {
      btn.innerHTML = orig;
      btn.disabled  = false;
      btn.style.background = '';
    }, 3200);
  });
}

function showToast() {
  const t = document.getElementById('toast');
  if (!t) return;
  t.classList.add('show');
  setTimeout(() => t.classList.remove('show'), 3200);
}

/* ══════════════════════════════════════════════
   SCROLL REVEAL (simple fade-in)
══════════════════════════════════════════════ */
function initScrollReveal() {
  const els = document.querySelectorAll(
    '.tl-card, .edu-card, .ach-card, .skill-cat, .info-item, .str-item, .contact-card'
  );
  els.forEach((el, i) => {
    el.style.opacity   = '0';
    el.style.transform = 'translateY(16px)';
    el.style.transition = `opacity .5s ease ${(i % 6) * 0.06}s, transform .5s ease ${(i % 6) * 0.06}s`;
  });

  const io = new IntersectionObserver(entries => {
    entries.forEach(e => {
      if (e.isIntersecting) {
        e.target.style.opacity   = '1';
        e.target.style.transform = 'translateY(0)';
        io.unobserve(e.target);
      }
    });
  }, { threshold: 0.1 });

  els.forEach(el => io.observe(el));
}
